version: '3.2'

services:
  download-mover:
    container_name: DownloadWatcher
    build: .
    restart: "no"
    volumes:
      - ./server:/server
      - ./appdata:/home/gradle/project/appdata
    environment:
      - PUID=1000
      - PGID=1000