/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`api_v3_manualimport_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV3ManualimportGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v3_manualimport_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV3ManualimportPostError {
    UnknownValue(serde_json::Value),
}


pub async fn api_v3_manualimport_get(configuration: &configuration::Configuration, folder: Option<&str>, download_id: Option<&str>, series_id: Option<i32>, season_number: Option<i32>, filter_existing_files: Option<bool>) -> Result<Vec<models::ManualImportResource>, Error<ApiV3ManualimportGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_folder = folder;
    let p_query_download_id = download_id;
    let p_query_series_id = series_id;
    let p_query_season_number = season_number;
    let p_query_filter_existing_files = filter_existing_files;

    let uri_str = format!("{}/api/v3/manualimport", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_folder {
        req_builder = req_builder.query(&[("folder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_download_id {
        req_builder = req_builder.query(&[("downloadId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series_id {
        req_builder = req_builder.query(&[("seriesId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_season_number {
        req_builder = req_builder.query(&[("seasonNumber", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_existing_files {
        req_builder = req_builder.query(&[("filterExistingFiles", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ManualImportResource&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ManualImportResource&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV3ManualimportGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn api_v3_manualimport_post(configuration: &configuration::Configuration, manual_import_reprocess_resource: Option<Vec<models::ManualImportReprocessResource>>) -> Result<(), Error<ApiV3ManualimportPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_manual_import_reprocess_resource = manual_import_reprocess_resource;

    let uri_str = format!("{}/api/v3/manualimport", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_manual_import_reprocess_resource);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV3ManualimportPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

